### ISSUE TITLE
CP32-- Implement Sign Detection Using Tensorflow(Weekly Meetings for COMP5615 Group 2 T17A)

### ISSUE THREAD

**Issue by aguh5894** [wallarug/capstone2020#3]
We would like to request the following time slots for weekly meetings:
Slot 1( Meeting at the beginning of the week): MON 8.30-9:00 pm
Slot 2( Meeting at the end of the week): THURS 8.30-9:00 pm

**Comment by wallarug** [comment]
Hi Aradhika,

Thank you for letting me know.  I've added these times now.
